"""Результат миграции"""
# Generated by Django 4.2.2 on 2023-07-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('customer_card_id',
                 models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateReports',
            fields=[
                ('analysis_formation',
                 models.DateField(blank=True,
                                  primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'date_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('sku_id', models.BigIntegerField(primary_key=True,
                                                  serialize=False)),
                ('sku_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupsOfGoods',
            fields=[
                ('group_id', models.BigIntegerField(primary_key=True,
                                                    serialize=False)),
                ('group_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups_of_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('customer_id',
                 models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_name',
                 models.CharField(blank=True, null=True)),
                ('customer_surname',
                 models.CharField(blank=True, null=True)),
                ('customer_primary_email',
                 models.CharField(blank=True, null=True)),
                ('customer_primary_phone',
                 models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('transaction_store_id',
                 models.BigIntegerField(blank=True, primary_key=True,
                                        serialize=False)),
                ('sku_purchase_price',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
                ('sku_retail_price',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id',
                 models.BigIntegerField(primary_key=True, serialize=False)),
                ('transaction_summ',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
                ('transaction_date_time', models.DateTimeField(blank=True,
                                                               null=True)),
                ('transaction_store_id', models.BigIntegerField(blank=True,
                                                                null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('transaction',
                 models.ForeignKey(blank=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING,  # noqa: E501
                                   primary_key=True, serialize=False,
                                   to='backend.transactions')),
                ('sku_amount',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
                ('sku_summ',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
                ('sku_summ_paid',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
                ('sku_discount',
                 models.DecimalField(blank=True, decimal_places=6,
                                     max_digits=10, null=True)),
            ],
            options={
                'db_table': 'checks',
                'managed': False,
            },
        ),
    ]
