"""Ассоциации url адресов с представлениями"""
from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name='home'),

    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout', views.logout_user, name='logout'),

    path('about', views.about, name='about'),
    path('about/developers', views.developers, name='developers'),

    path('data', views.data, name='data'),
    path('data/crud', views.crud, name='crud'),

    path('data/crud/view_cards',
         views.crud_view_cards, name='crud_view_cards'),
    path('data/crud/view_checks',
         views.crud_view_checks, name='crud_view_checks'),
    path('data/crud/view_date_reports', views.crud_view_date_reports,
         name='crud_view_date_reports'),
    path('data/crud/view_goods', views.crud_view_goods,
         name='crud_view_goods'),
    path('data/crud/view_groups_of_goods', views.crud_view_groups_of_goods,
         name='crud_view_groups_of_goods'),
    path('data/crud/view_personal_data', views.crud_view_personal_data,
         name='crud_view_personal_data'),
    path('data/crud/view_stores',
         views.crud_view_stores, name='crud_view_stores'),
    path('data/crud/view_transactions', views.crud_view_transactions,
         name='crud_view_transactions'),

    path('data/crud/create_cards',
         views.crud_create_cards, name='crud_create_cards'),
    path('data/crud/create_checks',
         views.crud_create_checks, name='crud_create_checks'),
    path('data/crud/create_date_reports', views.crud_create_date_reports,
         name='crud_create_date_reports'),
    path('data/crud/create_goods', views.crud_create_goods,
         name='crud_create_goods'),
    path('data/crud/create_groups_of_goods', views.crud_create_groups_of_goods,
         name='crud_create_groups_of_goods'),
    path('data/crud/create_personal_data', views.crud_create_personal_data,
         name='crud_create_personal_data'),
    path('data/crud/create_stores',
         views.crud_create_stores, name='crud_create_stores'),
    path('data/crud/create_transactions', views.crud_create_transactions,
         name='crud_create_transactions'),

    path('data/crud/update_cards',
         views.crud_update_cards, name='crud_update_cards'),
    path('data/crud/update_checks',
         views.crud_update_checks, name='crud_update_checks'),
    path('data/crud/update_date_reports', views.crud_update_date_reports,
         name='crud_update_date_reports'),
    path('data/crud/update_goods', views.crud_update_goods,
         name='crud_update_goods'),
    path('data/crud/update_groups_of_goods', views.crud_update_groups_of_goods,
         name='crud_update_groups_of_goods'),
    path('data/crud/update_personal_data', views.crud_update_personal_data,
         name='crud_update_personal_data'),
    path('data/crud/update_stores',
         views.crud_update_stores, name='crud_update_stores'),
    path('data/crud/update_transactions', views.crud_update_transactions,
         name='crud_update_transactions'),

    path('data/crud/delete_cards',
         views.crud_delete_cards, name='crud_delete_cards'),
    path('data/crud/delete_checks',
         views.crud_delete_checks, name='crud_delete_checks'),
    path('data/crud/delete_date_reports', views.crud_delete_date_reports,
         name='crud_delete_date_reports'),
    path('data/crud/delete_goods', views.crud_delete_goods,
         name='crud_delete_goods'),
    path('data/crud/delete_groups_of_goods', views.crud_delete_groups_of_goods,
         name='crud_delete_groups_of_goods'),
    path('data/crud/delete_personal_data', views.crud_delete_personal_data,
         name='crud_delete_personal_data'),
    path('data/crud/delete_stores',
         views.crud_delete_stores, name='crud_delete_stores'),
    path('data/crud/delete_transactions', views.crud_delete_transactions,
         name='crud_delete_transactions'),

    path('data/crud/import_cards',
         views.crud_import_cards, name='crud_import_cards'),
    path('data/crud/import_checks',
         views.crud_import_checks, name='crud_import_checks'),
    path('data/crud/import_date_reports', views.crud_import_date_reports,
         name='crud_import_date_reports'),
    path('data/crud/import_goods', views.crud_import_goods,
         name='crud_import_goods'),
    path('data/crud/import_groups_of_goods', views.crud_import_groups_of_goods,
         name='crud_import_groups_of_goods'),
    path('data/crud/import_personal_data', views.crud_import_personal_data,
         name='crud_import_personal_data'),
    path('data/crud/import_stores',
         views.crud_import_stores, name='crud_import_stores'),
    path('data/crud/import_transactions', views.crud_import_transactions,
         name='crud_import_transactions'),

    path('data/crud/export_cards',
         views.crud_export_cards, name='crud_export_cards'),
    path('data/crud/export_checks',
         views.crud_export_checks, name='crud_export_checks'),
    path('data/crud/export_date_reports', views.crud_export_date_reports,
         name='crud_export_date_reports'),
    path('data/crud/export_goods', views.crud_export_goods,
         name='crud_export_goods'),
    path('data/crud/export_groups_of_goods', views.crud_export_groups_of_goods,
         name='crud_export_groups_of_goods'),
    path('data/crud/export_personal_data', views.crud_export_personal_data,
         name='crud_export_personal_data'),
    path('data/crud/export_stores',
         views.crud_export_stores, name='crud_export_stores'),
    path('data/crud/export_transactions', views.crud_export_transactions,
         name='crud_export_transactions'),

    path('data/crud/update_cards/<pk>',
         views.CardsDetailView.as_view(),
         name='detail_view_cards'),
    path('data/crud/update_checks/<pk>',
         views.ChecksDetailView.as_view(),
         name='detail_view_checks'),
    path('data/crud/update_date_reports/<pk>',
         views.DateReportsDetailView.as_view(),
         name='detail_view_date_reports'),
    path('data/crud/update_goods/<pk>',
         views.GoodsDetailView.as_view(),
         name='detail_view_goods'),
    path('data/crud/update_groups/<pk>',
         views.GroupsOfGoodsDetailView.as_view(),
         name='detail_view_groups'),
    path('data/crud/update_personal/<pk>',
         views.PersonalDataDetailView.as_view(),
         name='detail_view_personal'),
    path('data/crud/update_stores/<slug>',
         views.StoresDetailView.as_view(),
         name='detail_view_stores'),
    path('data/crud/update_transactions/<pk>',
         views.TransactionsDetailView.as_view(),
         name='detail_view_transactions'),

    path('data/crud/update_cards/<pk>/update',
         views.CardsUpdateView.as_view(),
         name='detail_update_cards'),
    path('data/crud/update_checks/<pk>/update',
         views.ChecksUpdateView.as_view(),
         name='detail_update_checks'),
    path('data/crud/update_date_reports/<pk>/update',
         views.DateReportsUpdateView.as_view(),
         name='detail_update_date_reports'),
    path('data/crud/update_goods/<pk>/update',
         views.GoodsUpdateView.as_view(),
         name='detail_update_goods'),
    path('data/crud/update_groups/<pk>/update',
         views.GroupsOfGoodsUpdateView.as_view(),
         name='detail_update_groups'),
    path('data/crud/update_personal/<pk>/update',
         views.PersonalDataUpdateView.as_view(),
         name='detail_update_personal'),
    path('data/crud/update_stores/<slug>/update',
         views.StoresUpdateView.as_view(),
         name='detail_update_stores'),
    path('data/crud/update_transactions/<pk>/update',
         views.TransactionsUpdateView.as_view(),
         name='detail_update_transactions'),

    path('data/crud/delete_cards/<pk>/delete',
         views.CardsDeleteView.as_view(),
         name='detail_delete_cards'),
    path('data/crud/delete_checks/<pk>/delete',
         views.ChecksDeleteView.as_view(),
         name='detail_delete_checks'),
    path('data/crud/delete_date_reports/<pk>/delete',
         views.DateReportsDeleteView.as_view(),
         name='detail_delete_date_reports'),
    path('data/crud/delete_goods/<pk>/delete',
         views.GoodsDeleteView.as_view(),
         name='detail_delete_goods'),
    path('data/crud/delete_groups/<pk>/delete',
         views.GroupsOfGoodsDeleteView.as_view(),
         name='detail_delete_groups'),
    path('data/crud/delete_personal/<pk>/delete',
         views.PersonalDataDeleteView.as_view(),
         name='detail_delete_personal'),
    path('data/crud/delete_stores/<slug>/delete',
         views.StoresDeleteView.as_view(),
         name='detail_delete_stores'),
    path('data/crud/delete_transactions/<pk>/delete',
         views.TransactionsDeleteView.as_view(),
         name='detail_delete_transactions'),

    path('retail', views.retail, name='retail'),
    path('manual', views.manual, name='manual'),
    path('proposals', views.proposals, name='proposals'),
]
